services:
  webserver:
    image: apache/airflow:2.6.0-python3.9
    entrypoint: [ "bash", "/opt/airflow/script/entrypoint.sh" ]
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER_BASE_URL=http://localhost:8080
      - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./requirements.txt:/requirements.txt
      - ./wheels:/opt/airflow/wheels
      - ./data:/opt/airflow/data
      - ./pipelines:/opt/airflow/pipelines
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - confluent

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - confluent

  scheduler:
    image: apache/airflow:2.6.0-python3.9
    entrypoint: bash
    command: >
      -c "
      pip install --no-index --find-links=/opt/airflow/wheels -r /requirements.txt &&
      airflow db upgrade &&
      exec airflow scheduler
      "
    depends_on:
      webserver:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./wheels:/opt/airflow/wheels
      - ./data:/opt/airflow/data
      - ./pipelines:/opt/airflow/pipelines
    networks:
      - confluent

networks:
  confluent:
